version: "3.9"

services:
    payment_base_app:
        image: ghcr.io/l-m-digital/spay:latest
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            - postgres_db
        command: sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

    postgres_db:
        image: postgres:15.3-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
volumes:
    postgres_data:
