version: "3.9"

services:
    payment_base_app:
        image: ghcr.io/l-m-digital/spay:latest
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        networks:
            - sPay_network
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        volumes:
            - .:/app
            - ./logs/backend:/app/logs
        depends_on:
            - postgres_db
        command: sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

    postgres_db:
        image: postgres:15.3-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./logs/postgres/:/var/log/postgresql/
        command:
            [
                "postgres",
                "-c",
                "log_statement=all",
                "-c",
                "log_destination=stderr",
                "-c",
                "log_directory=/var/log",
                "-c",
                "log_filename=postgresql.log",
            ]
        env_file:
            - ./.env
        networks:
            - sPay_network

    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx:/etc/nginx/certs
        depends_on:
            - payment_base_app
        networks:
            - sPay_network

volumes:
    postgres_data:

networks:
    sPay_network:
        driver: bridge
