apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: payment-pvc
    namespace: tcc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
