apiVersion: v1
kind: Service
metadata:
    name: django-service
    namespace: tcc
spec:
    selector:
        app: payment-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
    type: LoadBalancer
