name: Testes

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Create .env file
              run: echo "${{ secrets.TESTS_ENV_FILE }}" > .env

            - name: Build and run Docker container
              run: docker-compose up -d
              working-directory: .

            - name: Run pytest tests
              run: docker-compose exec -T payment_base_app pytest
              working-directory: .

            - name: Stop Docker container
              run: docker-compose down
              working-directory: .
